/**
 * Shared types for the MOTO-XMR Coordinator.
 */

/** All possible states of a swap in the coordinator state machine. */
export enum SwapStatus {
    OPEN = 'OPEN',
    TAKEN = 'TAKEN',
    XMR_LOCKING = 'XMR_LOCKING',
    XMR_LOCKED = 'XMR_LOCKED',
    MOTO_CLAIMING = 'MOTO_CLAIMING',
    COMPLETED = 'COMPLETED',
    EXPIRED = 'EXPIRED',
    REFUNDED = 'REFUNDED',
}

/** Terminal states — no further transitions possible. */
export const TERMINAL_STATES: ReadonlySet<SwapStatus> = new Set([
    SwapStatus.COMPLETED,
    SwapStatus.REFUNDED,
]);

/** A swap record as stored in SQLite and returned by the API. */
export interface ISwapRecord {
    readonly id: number;
    readonly swap_id: string;
    readonly hash_lock: string;
    readonly preimage: string | null;
    readonly refund_block: number;
    readonly moto_amount: string;
    readonly xmr_amount: string;
    readonly xmr_address: string | null;
    readonly depositor: string;
    readonly counterparty: string | null;
    readonly status: SwapStatus;
    readonly opnet_create_tx: string | null;
    readonly opnet_claim_tx: string | null;
    readonly opnet_refund_tx: string | null;
    readonly xmr_lock_tx: string | null;
    readonly xmr_lock_confirmations: number;
    readonly created_at: string;
    readonly updated_at: string;
}

/** Fields used when creating a new swap record. */
export interface ICreateSwapParams {
    readonly swap_id: string;
    readonly hash_lock: string;
    readonly refund_block: number;
    readonly moto_amount: string;
    readonly xmr_amount: string;
    readonly xmr_address: string | null;
    readonly depositor: string;
    readonly opnet_create_tx: string | null;
}

/** Fields that can be updated on an existing swap. */
export interface IUpdateSwapParams {
    readonly status?: SwapStatus;
    readonly preimage?: string;
    readonly counterparty?: string;
    readonly opnet_claim_tx?: string;
    readonly opnet_refund_tx?: string;
    readonly xmr_lock_tx?: string;
    readonly xmr_lock_confirmations?: number;
    readonly xmr_address?: string;
}

/** A state history entry. */
export interface IStateHistoryEntry {
    readonly id: number;
    readonly swap_id: string;
    readonly from_state: string;
    readonly to_state: string;
    readonly timestamp: string;
    readonly metadata: string | null;
}

/** Preimage + hash lock pair generated by the Monero module. */
export interface IPreimageResult {
    readonly preimage: string;
    readonly hashLock: string;
}

/** Result of checking a Monero lock address. */
export interface IMonitorLockResult {
    readonly confirmations: number;
    readonly confirmed: boolean;
}

/** On-chain swap data returned by the OPNet watcher. */
export interface IOnChainSwap {
    readonly swapId: bigint;
    readonly hashLock: bigint;
    readonly refundBlock: bigint;
    readonly amount: bigint;
    readonly xmrAmount: bigint;
    readonly depositor: string;
    readonly counterparty: string;
    readonly status: bigint;
    readonly xmrAddressHi: bigint;
    readonly xmrAddressLo: bigint;
}

/** Preimage-ready WebSocket message payload. */
export interface IWsPreimageReady {
    readonly swapId: string;
    readonly preimage: string;
}

/** Incoming WebSocket message from client. */
export interface IWsClientMessage {
    readonly type: 'subscribe';
    readonly swapId: string;
}

/** WebSocket message shape. */
export interface IWsMessage {
    readonly type: 'swap_update' | 'active_swaps' | 'error' | 'preimage_ready';
    readonly data: ISwapRecord | ISwapRecord[] | string | IWsPreimageReady;
}

/** Structured API response wrapper. */
export interface IApiResponse<T> {
    readonly success: boolean;
    readonly data: T | null;
    readonly error: IApiError | null;
}

/** Structured API error. */
export interface IApiError {
    readonly code: string;
    readonly message: string;
    readonly retryable: boolean;
}

/** Pagination query params. */
export interface IPaginationParams {
    readonly page: number;
    readonly limit: number;
}

/** Request body for POST /api/swaps/:id/take */
export interface ITakeSwapBody {
    readonly opnetTxId: string;
}
